version: '3'
services:
    python:
        container_name: python
        build:
            context: ./
        volumes:
            - ./app:/app
        ports:
            - 8000:8000
        tty: true

    mysql:
        container_name: mariadb
        build:
            context: ./
            dockerfile: Dockerfile_mariadb
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./db:/var/lib/mysql
